### ISSUE TITLE
DFD Comments 2/20

### ISSUE THREAD

**Issue by germonprez** [jiahaoqi1/ISQA-3420#9]
1) These two dataflows are not needed: 

<img width="251" alt="screen shot 2017-02-20 at 3 15 00 pm" src="https://cloud.githubusercontent.com/assets/656208/23142024/6642dd2e-f77f-11e6-9450-d665c231cb2d.png">

2) This process needs to write the license and vulnerability data to the DB. 

<img width="115" alt="screen shot 2017-02-20 at 3 15 40 pm" src="https://cloud.githubusercontent.com/assets/656208/23142041/837aa0fc-f77f-11e6-93b7-4b001c0ec1b4.png">

This is what I currently see. 

MG

**Comment by jiahaoqi1** [comment]
I've made some changes to the DFD based on your comments. Take a look at my updated DFD and let me know if I need to make any more changes.
